[settings]
experimental = true
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true # enabled by default (unlike asdf)
# python-build
python_compile = true
idiomatic_version_file_enable_tools = ["node"]
lockfile = true

[tools]
# specify single or multiple versions
neovim = "latest"
deno = "latest"
lua-language-server = "latest"
delta = "latest"
chezmoi = "latest"
difftastic = "latest"
fzf = "latest"
golang = "latest"
docker-slim = "latest"
stylua = "latest"
usage = "latest"
eza = "latest"
direnv = "latest"

yq.version = "latest"
yq.postinstall = """
yq shell-completion bash > ~/.config/bash_completions.d/yq
yq shell-completion powershell > ~/.config/powershell/scripts/ArgumentCompleters/yq.ps1
"""
fx = "latest"
actionlint = "latest"
gum = "latest"
grype = "latest"
"aqua:zoxide" = "latest"
